// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: proto/smr.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageBlockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender   int64  `protobuf:"varint,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver int64  `protobuf:"varint,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Hash     string `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *MessageBlockRequest) Reset() {
	*x = MessageBlockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_smr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageBlockRequest) ProtoMessage() {}

func (x *MessageBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageBlockRequest.ProtoReflect.Descriptor instead.
func (*MessageBlockRequest) Descriptor() ([]byte, []int) {
	return file_proto_smr_proto_rawDescGZIP(), []int{0}
}

func (x *MessageBlockRequest) GetSender() int64 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *MessageBlockRequest) GetReceiver() int64 {
	if x != nil {
		return x.Receiver
	}
	return 0
}

func (x *MessageBlockRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type MessageBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender   int64                              `protobuf:"varint,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver int64                              `protobuf:"varint,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Hash     string                             `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"` // unique identifier specified by proposer for the block
	Requests []*MessageBlock_ClientRequestBatch `protobuf:"bytes,4,rep,name=requests,proto3" json:"requests,omitempty"`
}

func (x *MessageBlock) Reset() {
	*x = MessageBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_smr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageBlock) ProtoMessage() {}

func (x *MessageBlock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageBlock.ProtoReflect.Descriptor instead.
func (*MessageBlock) Descriptor() ([]byte, []int) {
	return file_proto_smr_proto_rawDescGZIP(), []int{1}
}

func (x *MessageBlock) GetSender() int64 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *MessageBlock) GetReceiver() int64 {
	if x != nil {
		return x.Receiver
	}
	return 0
}

func (x *MessageBlock) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *MessageBlock) GetRequests() []*MessageBlock_ClientRequestBatch {
	if x != nil {
		return x.Requests
	}
	return nil
}

type MessageBlockAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender   int64  `protobuf:"varint,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver int64  `protobuf:"varint,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Hash     string `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *MessageBlockAck) Reset() {
	*x = MessageBlockAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_smr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageBlockAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageBlockAck) ProtoMessage() {}

func (x *MessageBlockAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageBlockAck.ProtoReflect.Descriptor instead.
func (*MessageBlockAck) Descriptor() ([]byte, []int) {
	return file_proto_smr_proto_rawDescGZIP(), []int{2}
}

func (x *MessageBlockAck) GetSender() int64 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *MessageBlockAck) GetReceiver() int64 {
	if x != nil {
		return x.Receiver
	}
	return 0
}

func (x *MessageBlockAck) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type MessageBlock_SingleClientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *MessageBlock_SingleClientRequest) Reset() {
	*x = MessageBlock_SingleClientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_smr_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageBlock_SingleClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageBlock_SingleClientRequest) ProtoMessage() {}

func (x *MessageBlock_SingleClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smr_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageBlock_SingleClientRequest.ProtoReflect.Descriptor instead.
func (*MessageBlock_SingleClientRequest) Descriptor() ([]byte, []int) {
	return file_proto_smr_proto_rawDescGZIP(), []int{1, 0}
}

func (x *MessageBlock_SingleClientRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MessageBlock_ClientRequestBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender   int64                               `protobuf:"varint,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Requests []*MessageBlock_SingleClientRequest `protobuf:"bytes,2,rep,name=requests,proto3" json:"requests,omitempty"`
	Id       string                              `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"` // unique identifier specified by client for the client request batch
}

func (x *MessageBlock_ClientRequestBatch) Reset() {
	*x = MessageBlock_ClientRequestBatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_smr_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageBlock_ClientRequestBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageBlock_ClientRequestBatch) ProtoMessage() {}

func (x *MessageBlock_ClientRequestBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smr_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageBlock_ClientRequestBatch.ProtoReflect.Descriptor instead.
func (*MessageBlock_ClientRequestBatch) Descriptor() ([]byte, []int) {
	return file_proto_smr_proto_rawDescGZIP(), []int{1, 1}
}

func (x *MessageBlock_ClientRequestBatch) GetSender() int64 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *MessageBlock_ClientRequestBatch) GetRequests() []*MessageBlock_SingleClientRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *MessageBlock_ClientRequestBatch) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_proto_smr_proto protoreflect.FileDescriptor

var file_proto_smr_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x6d, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x5d, 0x0a, 0x13, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68,
	0x22, 0xc2, 0x02, 0x0a, 0x0c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x3c, 0x0a, 0x08, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x08, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x1a, 0x2f, 0x0a, 0x13, 0x53, 0x69, 0x6e, 0x67, 0x6c,
	0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x7b, 0x0a, 0x12, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x3d, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x08, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x59, 0x0a, 0x0f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x41, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68,
	0x42, 0x08, 0x5a, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_smr_proto_rawDescOnce sync.Once
	file_proto_smr_proto_rawDescData = file_proto_smr_proto_rawDesc
)

func file_proto_smr_proto_rawDescGZIP() []byte {
	file_proto_smr_proto_rawDescOnce.Do(func() {
		file_proto_smr_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_smr_proto_rawDescData)
	})
	return file_proto_smr_proto_rawDescData
}

var file_proto_smr_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_smr_proto_goTypes = []interface{}{
	(*MessageBlockRequest)(nil),              // 0: MessageBlockRequest
	(*MessageBlock)(nil),                     // 1: MessageBlock
	(*MessageBlockAck)(nil),                  // 2: MessageBlockAck
	(*MessageBlock_SingleClientRequest)(nil), // 3: MessageBlock.SingleClientRequest
	(*MessageBlock_ClientRequestBatch)(nil),  // 4: MessageBlock.ClientRequestBatch
}
var file_proto_smr_proto_depIdxs = []int32{
	4, // 0: MessageBlock.requests:type_name -> MessageBlock.ClientRequestBatch
	3, // 1: MessageBlock.ClientRequestBatch.requests:type_name -> MessageBlock.SingleClientRequest
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_smr_proto_init() }
func file_proto_smr_proto_init() {
	if File_proto_smr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_smr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageBlockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_smr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_smr_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageBlockAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_smr_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageBlock_SingleClientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_smr_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageBlock_ClientRequestBatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_smr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_smr_proto_goTypes,
		DependencyIndexes: file_proto_smr_proto_depIdxs,
		MessageInfos:      file_proto_smr_proto_msgTypes,
	}.Build()
	File_proto_smr_proto = out.File
	file_proto_smr_proto_rawDesc = nil
	file_proto_smr_proto_goTypes = nil
	file_proto_smr_proto_depIdxs = nil
}
