// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: proto/smr/smr.proto

package smr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageBlockReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash     int64                              `protobuf:"varint,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Requests []*MessageBlockReply_ClientRequest `protobuf:"bytes,2,rep,name=requests,proto3" json:"requests,omitempty"`
}

func (x *MessageBlockReply) Reset() {
	*x = MessageBlockReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_smr_smr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageBlockReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageBlockReply) ProtoMessage() {}

func (x *MessageBlockReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smr_smr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageBlockReply.ProtoReflect.Descriptor instead.
func (*MessageBlockReply) Descriptor() ([]byte, []int) {
	return file_proto_smr_smr_proto_rawDescGZIP(), []int{0}
}

func (x *MessageBlockReply) GetHash() int64 {
	if x != nil {
		return x.Hash
	}
	return 0
}

func (x *MessageBlockReply) GetRequests() []*MessageBlockReply_ClientRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type MessageBlockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash int64 `protobuf:"varint,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *MessageBlockRequest) Reset() {
	*x = MessageBlockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_smr_smr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageBlockRequest) ProtoMessage() {}

func (x *MessageBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smr_smr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageBlockRequest.ProtoReflect.Descriptor instead.
func (*MessageBlockRequest) Descriptor() ([]byte, []int) {
	return file_proto_smr_smr_proto_rawDescGZIP(), []int{1}
}

func (x *MessageBlockRequest) GetHash() int64 {
	if x != nil {
		return x.Hash
	}
	return 0
}

type MessageBlockReply_ClientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *MessageBlockReply_ClientRequest) Reset() {
	*x = MessageBlockReply_ClientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_smr_smr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageBlockReply_ClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageBlockReply_ClientRequest) ProtoMessage() {}

func (x *MessageBlockReply_ClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smr_smr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageBlockReply_ClientRequest.ProtoReflect.Descriptor instead.
func (*MessageBlockReply_ClientRequest) Descriptor() ([]byte, []int) {
	return file_proto_smr_smr_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MessageBlockReply_ClientRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessageBlockReply_ClientRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_smr_smr_proto protoreflect.FileDescriptor

var file_proto_smr_smr_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x6d, 0x72, 0x2f, 0x73, 0x6d, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa0, 0x01, 0x0a, 0x11, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x68,
	0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12,
	0x3c, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x1a, 0x39, 0x0a,
	0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x29, 0x0a, 0x13, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x68,
	0x61, 0x73, 0x68, 0x42, 0x0b, 0x5a, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x6d, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_smr_smr_proto_rawDescOnce sync.Once
	file_proto_smr_smr_proto_rawDescData = file_proto_smr_smr_proto_rawDesc
)

func file_proto_smr_smr_proto_rawDescGZIP() []byte {
	file_proto_smr_smr_proto_rawDescOnce.Do(func() {
		file_proto_smr_smr_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_smr_smr_proto_rawDescData)
	})
	return file_proto_smr_smr_proto_rawDescData
}

var file_proto_smr_smr_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_smr_smr_proto_goTypes = []interface{}{
	(*MessageBlockReply)(nil),               // 0: MessageBlockReply
	(*MessageBlockRequest)(nil),             // 1: MessageBlockRequest
	(*MessageBlockReply_ClientRequest)(nil), // 2: MessageBlockReply.ClientRequest
}
var file_proto_smr_smr_proto_depIdxs = []int32{
	2, // 0: MessageBlockReply.requests:type_name -> MessageBlockReply.ClientRequest
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_smr_smr_proto_init() }
func file_proto_smr_smr_proto_init() {
	if File_proto_smr_smr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_smr_smr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageBlockReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_smr_smr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageBlockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_smr_smr_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageBlockReply_ClientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_smr_smr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_smr_smr_proto_goTypes,
		DependencyIndexes: file_proto_smr_smr_proto_depIdxs,
		MessageInfos:      file_proto_smr_smr_proto_msgTypes,
	}.Build()
	File_proto_smr_smr_proto = out.File
	file_proto_smr_smr_proto_rawDesc = nil
	file_proto_smr_smr_proto_goTypes = nil
	file_proto_smr_smr_proto_depIdxs = nil
}
